# Generated by Django 5.2.6 on 2025-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='validation_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
